// Generated by CoffeeScript 1.7.1
define(function(require, exports, module) {
  "use strict";
  var $, RightScroll;
  $ = require('jquery');
  RightScroll = function() {
    var self;
    self = this;
    this.init = function() {
      var resizeTime, rightBarTop;
      rightBarTop = $('#J_sidebar').offset().top;
      resizeTime = null;
      return $(window).bind('scroll.right', function() {
        if (resizeTime) {
          clearTimeout(resizeTime);
        }
        return resizeTime = setTimeout(function() {
          if ($(this).scrollTop() >= rightBarTop) {
            return $('#J_sidebar').css('position', 'fixed');
          } else {
            return $('#J_sidebar').css('position', 'absolute');
          }
        }, 100);
      });
    };
  };
  module.exports = RightScroll;
});
