module.exports = {
  "success": true,
  "data": {
    "AvailableDates": [{
      "Date": "2016-08-31",
      "MinPrice": 8413,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-30",
      "MinPrice": 12718,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-29",
      "MinPrice": 11214,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-28",
      "MinPrice": 7489,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-27",
      "MinPrice": 10992,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-26",
      "MinPrice": 10880,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-25",
      "MinPrice": 7303,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-24",
      "MinPrice": 8011,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-23",
      "MinPrice": 12476,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-22",
      "MinPrice": 12477,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-21",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-20",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-19",
      "MinPrice": 11726,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-18",
      "MinPrice": 11787,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-17",
      "MinPrice": 13988,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-16",
      "MinPrice": 11082,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-15",
      "MinPrice": 11105,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-14",
      "MinPrice": 12787,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-13",
      "MinPrice": 14350,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-12",
      "MinPrice": 14382,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-11",
      "MinPrice": 11888,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-10",
      "MinPrice": 11859,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-09",
      "MinPrice": 12825,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-08",
      "MinPrice": 12743,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-07",
      "MinPrice": 12601,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-06",
      "MinPrice": 13015,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-05",
      "MinPrice": 13208,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-04",
      "MinPrice": 12968,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-03",
      "MinPrice": 12663,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-02",
      "MinPrice": 12952,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-08-01",
      "MinPrice": 13408,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-31",
      "MinPrice": 15109,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-30",
      "MinPrice": 14655,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-29",
      "MinPrice": 13004,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-28",
      "MinPrice": 12251,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-27",
      "MinPrice": 12626,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-26",
      "MinPrice": 13634,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-25",
      "MinPrice": 13046,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-24",
      "MinPrice": 13674,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-23",
      "MinPrice": 14737,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-22",
      "MinPrice": 12621,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-21",
      "MinPrice": 12626,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-20",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-19",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-18",
      "MinPrice": 13136,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-17",
      "MinPrice": 14591,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-16",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-15",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-14",
      "MinPrice": 13329,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-13",
      "MinPrice": 15143,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-12",
      "MinPrice": 13127,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-11",
      "MinPrice": 13141,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-10",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-09",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-08",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-07",
      "MinPrice": 16148,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-06",
      "MinPrice": 14870,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-05",
      "MinPrice": 12223,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-04",
      "MinPrice": 12475,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-03",
      "MinPrice": 13825,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-02",
      "MinPrice": 13884,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-07-01",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-30",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-29",
      "MinPrice": 11070,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-28",
      "MinPrice": 12396,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-27",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-26",
      "MinPrice": 10964,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-25",
      "MinPrice": 11458,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-24",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-23",
      "MinPrice": 8292,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-22",
      "MinPrice": 8595,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-21",
      "MinPrice": 8727,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-20",
      "MinPrice": 9330,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-19",
      "MinPrice": 9733,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-18",
      "MinPrice": 8860,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-17",
      "MinPrice": 8923,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-16",
      "MinPrice": 8358,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-15",
      "MinPrice": 6152,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-14",
      "MinPrice": 6293,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-13",
      "MinPrice": 8771,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-12",
      "MinPrice": 7881,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-11",
      "MinPrice": 5195,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-10",
      "MinPrice": 6173,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-09",
      "MinPrice": 8119,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-08",
      "MinPrice": 7164,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-07",
      "MinPrice": 6837,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-06",
      "MinPrice": 8004,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-05",
      "MinPrice": 10000,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-04",
      "MinPrice": 10511,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-03",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-02",
      "MinPrice": 6406,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-06-01",
      "MinPrice": 4616,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-31",
      "MinPrice": 5817,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-30",
      "MinPrice": 7185,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-29",
      "MinPrice": 5698,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-28",
      "MinPrice": 4765,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-27",
      "MinPrice": 6189,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-26",
      "MinPrice": 5604,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-25",
      "MinPrice": 4339,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-24",
      "MinPrice": 5024,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-23",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-22",
      "MinPrice": 5040,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-21",
      "MinPrice": 4538,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-20",
      "MinPrice": 7037,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-19",
      "MinPrice": 6821,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-18",
      "MinPrice": 4230,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-17",
      "MinPrice": 4695,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-16",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-15",
      "MinPrice": 4624,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-14",
      "MinPrice": 4571,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-13",
      "MinPrice": 7534,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-12",
      "MinPrice": 0,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-11",
      "MinPrice": 6198,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-10",
      "MinPrice": 7206,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-09",
      "MinPrice": 12572,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-08",
      "MinPrice": 6866,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }, {
      "Date": "2016-05-07",
      "MinPrice": 6770,
      "RiskRemark": null,
      "RiskReward": 0,
      "IsPriceLowest": false
    }],
    "EndDate": "2016-08-31",
    "FestivalsDates": [{
      "FestivalDate": "2016-06-09",
      "FestivalName": "端午节",
      "FestivalType": 0,
      "OfflineShow": false,
      "OnlineShow": false
    }, {
      "FestivalDate": "2016-06-10",
      "FestivalName": "端午节",
      "FestivalType": 0,
      "OfflineShow": false,
      "OnlineShow": false
    }, {
      "FestivalDate": "2016-06-11",
      "FestivalName": "端午节",
      "FestivalType": 0,
      "OfflineShow": false,
      "OnlineShow": false
    }],
    "ProhibitDates": null,
    "StartDate": "2016-05-07",
    "MinPriceDay": "2016-05-18",
    "RetryDate": "2016-05-25"
  },
  "info": "获取成功"
}