// Generated by CoffeeScript 1.7.1

/*
 * 详情页邮轮逻辑模块
 */
define(function(require, exports, module) {
  "use strict";
  var $, Cruise, GLOBAL;
  $ = require('jquery');
  GLOBAL = {};
  Cruise = function() {
    this._getData = function() {};
  };
  module.exports = Cruise;
});
