// Generated by CoffeeScript 1.7.1

/*
 * 加入收藏
 * @author: jiang.f@ctrip.com
 * @date: 2014-03-25
 */
define(function(require, exports, module) {
  var $, Addfav;
  $ = require('jquery');
  Addfav = function() {
    var self;
    self = this;
    this._add = function(id, title, url) {
      var e;
      try {
        window.external.addFavorite(url, title);
      } catch (_error) {
        e = _error;
        try {
          $(id).attr('title', title).attr('href', url);
          window.sidebar.addPanel(title, url, "");
        } catch (_error) {
          e = _error;
          if (navigator.userAgent.indexOf("Firefox") > -1) {
            return;
          } else {
            $(id).attr('href', 'javascript:;');
            alert("加入收藏失败，请使用Ctrl+D手工添加");
          }
        }
      }
    };

    /*
     * @param {String} id             容器id
     * @param {Object} options       (可选)配置参数,不写为收藏当前页面url和标题
     *    @param {String} title      (可选)收藏标题
     *    @param {String} url        (可选)收藏url
     */
    this.init = function(id, options) {
      var title, url;
      title = document.title;
      url = document.location.href;
      if (options) {
        title = options.title || title;
        url = options.url || url;
      }
      $(document).delegate(id, 'click', function() {
        self._add(this, title, url);
      });
    };
  };
  module.exports = Addfav;
});
