module.exports = {
  "data": [{
    "ParentId": 2,
    "RegionID": 112,
    "RegionName": "静安区"
  }, {
    "ParentId": 2,
    "RegionID": 113,
    "RegionName": "徐汇区"
  }, {
    "ParentId": 2,
    "RegionID": 114,
    "RegionName": "长宁区"
  }, {
    "ParentId": 2,
    "RegionID": 115,
    "RegionName": "黄浦区"
  }, {
    "ParentId": 2,
    "RegionID": 116,
    "RegionName": "虹口区"
  }, {
    "ParentId": 2,
    "RegionID": 117,
    "RegionName": "宝山区"
  }, {
    "ParentId": 2,
    "RegionID": 118,
    "RegionName": "闸北区"
  }, {
    "ParentId": 2,
    "RegionID": 119,
    "RegionName": "浦东新区"
  }, {
    "ParentId": 2,
    "RegionID": 120,
    "RegionName": "普陀区"
  }, {
    "ParentId": 2,
    "RegionID": 121,
    "RegionName": "杨浦区"
  }, {
    "ParentId": 2,
    "RegionID": 122,
    "RegionName": "闵行区"
  }, {
    "ParentId": 2,
    "RegionID": 123,
    "RegionName": "嘉定区"
  }, {
    "ParentId": 2,
    "RegionID": 125,
    "RegionName": "松江区"
  }, {
    "ParentId": 2,
    "RegionID": 128,
    "RegionName": "青浦区"
  }, {
    "ParentId": 2,
    "RegionID": 133,
    "RegionName": "奉贤区"
  }, {
    "ParentId": 2,
    "RegionID": 134,
    "RegionName": "崇明"
  }],
  "errno": 0,
  "errmsg": "Success"
}