module.exports = {
  "errmsg": "OK",
  "errno": 0,
  "data": {
    "CustomerInfoItems": [{
        "CustomerInfoItemID": 24,
        "CustomerInfoItemModel": 2,
        "CustomerInfoItemType": "22",
        "Name": "台湾通行证",
        "RegEx": "",
        "Note": null,
        "SortNumber": 0,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 3,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "UserName",
        "Name": "姓名",
        "RegEx": "",
        "Note": null,
        "SortNumber": 3,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 4,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "Nationality",
        "Name": "国籍",
        "RegEx": "",
        "Note": null,
        "SortNumber": 4,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 5,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "IDType",
        "Name": "证件类型",
        "RegEx": "",
        "Note": null,
        "SortNumber": 5,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 6,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "Sex",
        "Name": "性别",
        "RegEx": "",
        "Note": null,
        "SortNumber": 6,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 7,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "IDNumber",
        "Name": "证件号",
        "RegEx": "",
        "Note": null,
        "SortNumber": 7,
        "IsRequired": false
      }, {
        "CustomerInfoItemID": 8,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "Birthday",
        "Name": "出生日期",
        "RegEx": "",
        "Note": null,
        "SortNumber": 8,
        "IsRequired": false
      }, {
        "CustomerInfoItemID": 10,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "CardValidUntil",
        "Name": "证件有效期",
        "RegEx": "",
        "Note": null,
        "SortNumber": 10,
        "IsRequired": false
      }, {
        "CustomerInfoItemID": 11,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "ContactPhone",
        "Name": "联系电话",
        "RegEx": "",
        "Note": null,
        "SortNumber": 11,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 18,
        "CustomerInfoItemModel": 2,
        "CustomerInfoItemType": "7",
        "Name": "回乡证",
        "RegEx": "",
        "Note": null,
        "SortNumber": 18,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 30,
        "CustomerInfoItemModel": 2,
        "CustomerInfoItemType": "100",
        "Name": "稍后提供",
        "RegEx": "",
        "Note": null,
        "SortNumber": 30,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 40,
        "CustomerInfoItemModel": 1,
        "CustomerInfoItemType": "CustomerType",
        "Name": "客户类别",
        "RegEx": "",
        "Note": null,
        "SortNumber": 31,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 46,
        "CustomerInfoItemModel": 3,
        "CustomerInfoItemType": "Below_2",
        "Name": "18周岁以下",
        "RegEx": "",
        "Note": null,
        "SortNumber": 37,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 47,
        "CustomerInfoItemModel": 3,
        "CustomerInfoItemType": "Between_2",
        "Name": "18周岁（含）至20周岁",
        "RegEx": "",
        "Note": null,
        "SortNumber": 38,
        "IsRequired": true
      }, {
        "CustomerInfoItemID": 48,
        "CustomerInfoItemModel": 3,
        "CustomerInfoItemType": "Above_2",
        "Name": "20周岁（含）以上",
        "RegEx": "",
        "Note": null,
        "SortNumber": 39,
        "IsRequired": true
      }],
    "FillInNumberLimit": "A",
    "IsVisaBySelf": false
  }
}