module.exports = {
  "data": [{
    "ParentId": 1,
    "RegionID": 1,
    "RegionName": "北京"
  }, {
    "ParentId": 1,
    "RegionID": 2,
    "RegionName": "上海"
  }, {
    "ParentId": 1,
    "RegionID": 3,
    "RegionName": "天津"
  }, {
    "ParentId": 1,
    "RegionID": 4,
    "RegionName": "重庆"
  }, {
    "ParentId": 1,
    "RegionID": 5,
    "RegionName": "黑龙江"
  }, {
    "ParentId": 1,
    "RegionID": 6,
    "RegionName": "吉林"
  }, {
    "ParentId": 1,
    "RegionID": 7,
    "RegionName": "辽宁"
  }, {
    "ParentId": 1,
    "RegionID": 8,
    "RegionName": "河北"
  }, {
    "ParentId": 1,
    "RegionID": 9,
    "RegionName": "河南"
  }, {
    "ParentId": 1,
    "RegionID": 10,
    "RegionName": "山东"
  }, {
    "ParentId": 1,
    "RegionID": 11,
    "RegionName": "山西"
  }, {
    "ParentId": 1,
    "RegionID": 12,
    "RegionName": "陕西"
  }, {
    "ParentId": 1,
    "RegionID": 13,
    "RegionName": "甘肃"
  }, {
    "ParentId": 1,
    "RegionID": 14,
    "RegionName": "宁夏"
  }, {
    "ParentId": 1,
    "RegionID": 15,
    "RegionName": "江苏"
  }, {
    "ParentId": 1,
    "RegionID": 16,
    "RegionName": "浙江"
  }, {
    "ParentId": 1,
    "RegionID": 17,
    "RegionName": "安徽"
  }, {
    "ParentId": 1,
    "RegionID": 18,
    "RegionName": "江西"
  }, {
    "ParentId": 1,
    "RegionID": 19,
    "RegionName": "福建"
  }, {
    "ParentId": 1,
    "RegionID": 20,
    "RegionName": "湖北"
  }, {
    "ParentId": 1,
    "RegionID": 21,
    "RegionName": "湖南"
  }, {
    "ParentId": 1,
    "RegionID": 22,
    "RegionName": "四川"
  }, {
    "ParentId": 1,
    "RegionID": 23,
    "RegionName": "广东"
  }, {
    "ParentId": 1,
    "RegionID": 24,
    "RegionName": "广西"
  }, {
    "ParentId": 1,
    "RegionID": 25,
    "RegionName": "云南"
  }, {
    "ParentId": 1,
    "RegionID": 26,
    "RegionName": "贵州"
  }, {
    "ParentId": 1,
    "RegionID": 27,
    "RegionName": "青海"
  }, {
    "ParentId": 1,
    "RegionID": 28,
    "RegionName": "内蒙古"
  }, {
    "ParentId": 1,
    "RegionID": 29,
    "RegionName": "新疆"
  }, {
    "ParentId": 1,
    "RegionID": 30,
    "RegionName": "西藏"
  }, {
    "ParentId": 1,
    "RegionID": 31,
    "RegionName": "海南"
  }, {
    "ParentId": 1,
    "RegionID": 32,
    "RegionName": "香港"
  }, {
    "ParentId": 1,
    "RegionID": 33,
    "RegionName": "澳门"
  }, {
    "ParentId": 1,
    "RegionID": 53,
    "RegionName": "台湾"
  }],
  "errno": 0,
  "errmsg": "Success"
}