module.exports = {
    "errmsg": "OK",
    "errno": 0,
    "data": {
        "Invoice": {
            "Content": [{
                "Key": 1,
                "Value": "旅游服务费"
            }, {
                "Key": 4,
                "Value": "签证费"
            }, {
                "Key": 8,
                "Value": "机票＋酒店"
            }, {
                "Key": 128,
                "Value": "服务费（代为租车服务）"
            }, {
                "Key": 512,
                "Value": "台湾团队旅游费"
            }, {
                "Key": 1024,
                "Value": "服务费"
            }],
            "MyInvoices": [{
                "Key": 14756,
                "Value": "你好发票"
            }, {
                "Key": 14755,
                "Value": "报销发票"
            }, {
                "Key": 14752,
                "Value": "发票抬头"
            }, {
                "Key": 14751,
                "Value": "asdf"
            }, {
                "Key": 14748,
                "Value": "携程旅行网"
            }, {
                "Key": 14738,
                "Value": "有发票普通的"
            }, {
                "Key": 14731,
                "Value": "dfds"
            }, {
                "Key": 14730,
                "Value": "dfdfs"
            }, {
                "Key": 14729,
                "Value": "dfdfh"
            }, {
                "Key": 14728,
                "Value": "dfdfg"
            }, {
                "Key": 14727,
                "Value": "dfdfer"
            }, {
                "Key": 14726,
                "Value": "dfdf5"
            }, {
                "Key": 14725,
                "Value": "dfdf4"
            }, {
                "Key": 14724,
                "Value": "dfdf3"
            }, {
                "Key": 14723,
                "Value": "dfdfe"
            }, {
                "Key": 14694,
                "Value": "HHIBJKK1156"
            }, {
                "Key": 14695,
                "Value": "后悔过海边"
            }, {
                "Key": 14659,
                "Value": "dfdf"
            }, {
                "Key": 14658,
                "Value": "dfdsfdf"
            }, {
                "Key": 14656,
                "Value": "dfd"
            }],
            "InvoiceDesc": "您的发票将于返程后5个工作日内开具并邮寄给您，请注意查收。",
            "IsSupportEinvoice": true
        },
        "DeliveryReult": {
            "SelfPickupAddress": ["上海市长宁区福泉路99号收发室", "上海北京西路1465号(常德路口)国立大厦1611室(9:00-21:00)"],
            "CityCanton": [{
                "Key": 17,
                "Value": "长宁区"
            }, {
                "Key": 18,
                "Value": "普陀区"
            }, {
                "Key": 19,
                "Value": "杨浦区"
            }, {
                "Key": 20,
                "Value": "闸北区"
            }, {
                "Key": 21,
                "Value": "虹口区"
            }, {
                "Key": 22,
                "Value": "徐汇区"
            }, {
                "Key": 23,
                "Value": "静安区"
            }, {
                "Key": 24,
                "Value": "卢湾区"
            }, {
                "Key": 25,
                "Value": "黄浦区"
            }, {
                "Key": 26,
                "Value": "闵行区"
            }, {
                "Key": 27,
                "Value": "嘉定区"
            }, {
                "Key": 28,
                "Value": "宝山区"
            }, {
                "Key": 29,
                "Value": "松江区"
            }, {
                "Key": 30,
                "Value": "浦东新区"
            }, {
                "Key": 31,
                "Value": "南汇区（暂未开通）"
            }, {
                "Key": 32,
                "Value": "奉贤区（暂未开通）"
            }, {
                "Key": 33,
                "Value": "青浦区"
            }, {
                "Key": 34,
                "Value": "金山区"
            }, {
                "Key": 35,
                "Value": "崇明县（暂未开通）"
            }],
            "DeliveryInfoList": [{
                "isHasInvoice": 1,
                "DeliveryGoodsDescriptions": ["发票"],
                "DeliveryType": [{
                    "DeliveryAmount": 10.0,
                    "DeliveryType": 1,
                    "IsSupportIntegralDelivery": true,
                    "IntegralDeliverAmount": 0.0
                },{
                    "DeliveryAmount": 10.0,
                    "DeliveryType": 3,
                    "IsSupportIntegralDelivery": true,
                    "IntegralDeliverAmount": 0.0
                }]
            }],
            "MyEMSAddress": [{
                "InfoId": 64675,
                "Address": "福泉路99号",
                "ProvinceId": 11,
                "ProvinceName": "上海",
                "CityId": 136,
                "CityName": "上海",
                "CantonID": 1468,
                "CantonName": "南郊区",
                "Post": "233333",
                "Recipient": "孙亮",
                "Tel": "13482652476",
                "Mobile": "13482652476"
            }, {
                "InfoId": 68449,
                "Address": "发射点发射得分的顶顶顶顶顶的顶顶顶顶顶顶顶顶顶顶顶顶顶顶顶",
                "ProvinceId": 2,
                "ProvinceName": "黑龙江",
                "CityId": 2,
                "CityName": "齐齐哈尔市",
                "CantonID": 114,
                "CantonName": "长宁区",
                "Post": "132001",
                "Recipient": "过热",
                "Tel": "13333334444",
                "Mobile": ""
            }, {
                "InfoId": 68454,
                "Address": "三大发射点发",
                "ProvinceId": 2,
                "ProvinceName": "黑龙江",
                "CityId": 2,
                "CityName": "哈尔滨市",
                "CantonID": 113,
                "CantonName": "徐汇区",
                "Post": "132001",
                "Recipient": "第三方",
                "Tel": "13344445555",
                "Mobile": ""
            }, {
                "InfoId": 68326,
                "Address": "崔巍最新的地址no1，史蒂芬，库里",
                "ProvinceId": 1,
                "ProvinceName": "北京",
                "CityId": 1,
                "CityName": "北京市",
                "CantonID": 92,
                "CantonName": "西城区",
                "Post": "110011",
                "Recipient": "崔巍",
                "Tel": "13444449999",
                "Mobile": ""
            }, {
                "InfoId": 69045,
                "Address": "北京东路9999号",
                "ProvinceId": 2,
                "ProvinceName": "上海",
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": "002211",
                "Recipient": "张三",
                "Tel": "15878954632",
                "Mobile": "15878954632"
            }, {
                "InfoId": 68460,
                "Address": "使得房贷首付",
                "ProvinceId": 13,
                "ProvinceName": "甘肃",
                "CityId": 326,
                "CityName": "嘉峪关市",
                "CantonID": 11123,
                "CantonName": "峪泉镇",
                "Post": "132001",
                "Recipient": "防守对方",
                "Tel": "13333334444",
                "Mobile": ""
            }, {
                "InfoId": 73438,
                "Address": "测好地市",
                "ProvinceId": 0,
                "ProvinceName": "江西省",
                "CityId": 0,
                "CityName": "南昌市",
                "CantonID": 0,
                "CantonName": "东湖区",
                "Post": "201615",
                "Recipient": "测试",
                "Tel": "",
                "Mobile": "15011112222"
            }, {
                "InfoId": 68474,
                "Address": "第三方地方",
                "ProvinceId": 5,
                "ProvinceName": "黑龙江",
                "CityId": 149,
                "CityName": "齐齐哈尔市",
                "CantonID": 873,
                "CantonName": "龙沙区",
                "Post": "132001",
                "Recipient": "斯蒂芬库里",
                "Tel": "13333334444",
                "Mobile": ""
            }, {
                "InfoId": 69243,
                "Address": "测试",
                "ProvinceId": 2,
                "ProvinceName": "上海",
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 117,
                "CantonName": "宝山区",
                "Post": "200000",
                "Recipient": "测试",
                "Tel": "15000013664",
                "Mobile": "15000013664"
            }, {
                "InfoId": 69805,
                "Address": "ces ",
                "ProvinceId": 2,
                "ProvinceName": "上海",
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 119,
                "CantonName": "浦东新区",
                "Post": "226200",
                "Recipient": "ces ",
                "Tel": "15000013664",
                "Mobile": "15000013664"
            }],
            "InCityDelivery": [{
                "InfoId": 69194,
                "Address": "tst",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 60586,
                "Address": "上海上海test",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "安庆市",
                "CantonID": 0,
                "CantonName": "潜山县",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 69105,
                "Address": "11111111",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 114,
                "CantonName": "长宁区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 61009,
                "Address": "长宁麻辣小龙虾",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海",
                "CantonID": 17,
                "CantonName": "长宁区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 57111,
                "Address": "地方",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "牡丹江市",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 52940,
                "Address": "上海fghfghfdgh阿斯蒂芬",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 56156,
                "Address": "上海市长宁区服软苦",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 61841,
                "Address": "立即入库配送地址",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 115,
                "CantonName": "徐汇区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 61838,
                "Address": "正常入库配送地址",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }, {
                "InfoId": 61033,
                "Address": "假定嘉定家丁",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海",
                "CantonID": 27,
                "CantonName": "嘉定区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }],
            "CityName": "上海"
        },
        "PickUpInfos": [],
        "Reminder": null,
        "IsVisa": false
    }
}