// Generated by CoffeeScript 1.7.1
define(function(require, exports, module) {
  "use strict";
  var $, RightScroll;
  $ = require('jquery');
  RightScroll = function() {
    var self;
    self = this;
    this.init = function() {
      var docHeight, hasBottom, resizeTime, rightBarTop, rightHeight;
      rightBarTop = $('#J_sidebar').offset().top;
      rightHeight = $('#J_sidebar').height();
      docHeight = $(document).height();
      resizeTime = null;
      hasBottom = true;
      $(window).bind('scroll.right', function() {
        if (docHeight > 1200) {
          if ($(this).scrollTop() >= rightBarTop) {
            if (($(this).scrollTop() + rightHeight) + 200 >= docHeight) {
              if (hasBottom) {
                $('#J_sidebar').css({
                  'position': 'absolute',
                  'top': $('#J_sidebar').offset().top - 522
                });
                hasBottom = false;
              }
            } else {
              $('#J_sidebar').css({
                'position': 'fixed',
                'top': 0
              });
              hasBottom = true;
            }
          } else {
            $('#J_sidebar').removeAttr('style');
            hasBottom = true;
          }
        }
      });
    };
  };
  module.exports = RightScroll;
});
